### Build in function:-

In [6]:
# 1.print():- To display the output.
print('hello suman')

hello suman


In [5]:
# 2.len():- return no of element in a sequence.
len([2,2,5,7,2,9,5,5,89])

9

In [8]:
# 3.sum():- return add all element in a sequence.
sum([2,2,5,7,2,9,5,5,89])

126

In [23]:
# 4.min():- return minimum value element in a sequence.
min([2,2,5,7,2,9,5,5,89])

2

In [24]:
# 5.max():- return maximum value element in a sequence.
max([2,2,5,7,2,9,5,5,89])

89

In [25]:
# 6. type():- rturn the data type of any function.
type([2,2,5,7,2,9,5,5,89])

list

In [26]:
# 6. id():- return the address location of any function.
max([2,2,5,7,2,9,5,5,89])

89

In [31]:
# 6. range():- return the data type of a function
range({3,7})

TypeError: 'set' object cannot be interpreted as an integer

In [30]:
# ord(character):- return ascii value of the character.
ord('a')

97

In [16]:
# chr(ascii_value):return character associate with ascii_value.
chr(33)

'!'

In [15]:
# pow(base,expo):- Return power of the function
pow(5,4)

625

# Numpy:- Numerical python
<pre>Numpy is library of python that helps us to deals with arrays and to do various mathematical operation on it</pre>
<pre>Array is a collection of homogenous value(having similar datatypes),mutablr(can be modified/changed),ehich is declrear using []. arrays are an ordered sequence(have fixed index position)</pre>


In [3]:
# importing the library to our environment.
import numpy as np

In [4]:
# to check the version of numpy:-
np.__version__

'2.2.3'

In [37]:
# creating a 1D array:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [38]:
# type():
type(a)

numpy.ndarray

In [42]:
# creating an array from tuple:
tup = (1,55,77,33,88)
tup

(1, 55, 77, 33, 88)

In [46]:
b = np.array(tup)
b

array([ 1, 55, 77, 33, 88])

In [55]:
c = np.array((1,2,3,'apple'))
c

array(['1', '2', '3', 'apple'], dtype='<U21')

In [58]:
e = np.array((1,2,3,'apple','suman'))
e     # so, can not be changed uncode

array(['1', '2', '3', 'apple', 'suman'], dtype='<U21')

In [61]:
# creating an array from dictionary:
dic = {1:22,2:43,7:32}
b = np.array(dic)
b

array({1: 22, 2: 43, 7: 32}, dtype=object)

In [63]:
# creating an array from set:
set = {1,55,77,33,88}
x = np.array(set)
x

array({1, 33, 55, 88, 77}, dtype=object)

In [66]:
# 2D Array :-
# creating a 2D array:-
arr = np.array([[1,2,3,4], [5,6,7,8]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [75]:
d2 = np.array([[8,9,10,11],[1,2,3,4],[6,7,12,13],[14,15,16,17]])
print(d2)
print('2nd element on 1st row: ', d2[0, 1])
print('3rd element on 4th row: ', d2[3, 3])

[[ 8  9 10 11]
 [ 1  2  3  4]
 [ 6  7 12 13]
 [14 15 16 17]]
2nd element on 1st row:  9
3rd element on 4th row:  17


In [78]:
# 3x3 matrix using tuple:-
np.array([(8,9,10,11),(1,2,3,4),(6,7,12,13)])

array([[ 8,  9, 10, 11],
       [ 1,  2,  3,  4],
       [ 6,  7, 12, 13]])

In [188]:
# 2x2 matrix using list:-
np.array([[8,9,10,11],[1,2,3,4]])

array([[ 8,  9, 10, 11],
       [ 1,  2,  3,  4]])

In [84]:
# 2x2 matrix using tuple and list:-
np.array([(8,9,10,11),[6,7,12,13]])

array([[ 8,  9, 10, 11],
       [ 6,  7, 12, 13]])

In [85]:
# array attribute
# to find the shape
x = np.array([(8,9,10,11),[6,7,12,13]])
x.shape

(2, 4)

In [86]:
# to find the size of an array
x = np.array([(8,9,10,11),[6,7,12,13]])
x.size

8

In [88]:
# to find the dimension of an array.
x = np.array([(8,9,10,11),[6,7,12,13]])
x.ndim

2

In [1]:
# creating an array of diff. lengths.
x = np.array([[8,9,10,11],[1,2,3,4],[6,7,12]])
x

NameError: name 'np' is not defined

In [94]:
# arange(): generates numbers between the given interval
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
# create an array of 3x2 where all values are 0.
x = np.array([[0,0],[0,0],[0,0]])
x

array([[0, 0],
       [0, 0],
       [0, 0]])

In [97]:
# np.zeros:- ti generates an 0's array.
np.zeros(4)

array([0., 0., 0., 0.])

In [114]:
z = np.zeros((4,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [112]:
z.dtype()

TypeError: 'numpy.dtypes.Float64DType' object is not callable

In [104]:
np.zeros((4,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [105]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [109]:
np.zeros((4,3),dtype='double')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [111]:
x = np.zeros((4,3))
x.astype(int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [116]:
# one :- cretes an array with all values as 1.
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [117]:
np.ones((6,6),dtype=int)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [119]:
# full():- creates an array where values are specific.
np.full((5,5),50)

array([[50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50]])

In [121]:
np.full((5,5),'❌❌✅')

array([['❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅'],
       ['❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅'],
       ['❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅'],
       ['❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅'],
       ['❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅', '❌❌✅']], dtype='<U3')

In [122]:
# linspace() :- generates equally distributed values.
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [123]:
np.linspace(1,100,56)

array([  1. ,   2.8,   4.6,   6.4,   8.2,  10. ,  11.8,  13.6,  15.4,
        17.2,  19. ,  20.8,  22.6,  24.4,  26.2,  28. ,  29.8,  31.6,
        33.4,  35.2,  37. ,  38.8,  40.6,  42.4,  44.2,  46. ,  47.8,
        49.6,  51.4,  53.2,  55. ,  56.8,  58.6,  60.4,  62.2,  64. ,
        65.8,  67.6,  69.4,  71.2,  73. ,  74.8,  76.6,  78.4,  80.2,
        82. ,  83.8,  85.6,  87.4,  89.2,  91. ,  92.8,  94.6,  96.4,
        98.2, 100. ])

In [125]:
# np.linspace(startrange,endrange,no.of values)
np.linspace(1,500,100)

array([  1.        ,   6.04040404,  11.08080808,  16.12121212,
        21.16161616,  26.2020202 ,  31.24242424,  36.28282828,
        41.32323232,  46.36363636,  51.4040404 ,  56.44444444,
        61.48484848,  66.52525253,  71.56565657,  76.60606061,
        81.64646465,  86.68686869,  91.72727273,  96.76767677,
       101.80808081, 106.84848485, 111.88888889, 116.92929293,
       121.96969697, 127.01010101, 132.05050505, 137.09090909,
       142.13131313, 147.17171717, 152.21212121, 157.25252525,
       162.29292929, 167.33333333, 172.37373737, 177.41414141,
       182.45454545, 187.49494949, 192.53535354, 197.57575758,
       202.61616162, 207.65656566, 212.6969697 , 217.73737374,
       222.77777778, 227.81818182, 232.85858586, 237.8989899 ,
       242.93939394, 247.97979798, 253.02020202, 258.06060606,
       263.1010101 , 268.14141414, 273.18181818, 278.22222222,
       283.26262626, 288.3030303 , 293.34343434, 298.38383838,
       303.42424242, 308.46464646, 313.50505051, 318.54

In [128]:
#identity matrix :-
np.eye(6,dtype='int')

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [129]:
#identity matrix :-
np.identity(7,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [186]:
# Random Number in an array.
# Random.rand():-generate a random number between 0~1.
np.random.rand()

0.2441452257659409

In [174]:
# creating a 1d array 
np.random.rand(6)

array([0.67772682, 0.37750892, 0.9256709 , 0.96749146, 0.5869871 ,
       0.51816708])

In [131]:
np.random.rand(3,4)

array([[0.37355461, 0.79039889, 0.27331683, 0.92056354],
       [0.81005015, 0.02764154, 0.53859661, 0.86269137],
       [0.48501686, 0.90108724, 0.18058534, 0.89499746]])

In [134]:
# random.randint(): generate random integer value.
np.random.randint(1,20)

19

In [137]:
np.random.randint(1,20,(4,6))

array([[ 8,  3, 11, 19, 19, 11],
       [17, 16, 16, 10,  7, 13],
       [12, 12,  7,  8,  4, 13],
       [ 8, 19, 16,  1,  4, 17]], dtype=int32)

In [139]:
# mathematical operations on array:-
a = np.array([2,22,4,5,6])
b = np.array([24,2,44,56,6])
print(a)
print(b)

[ 2 22  4  5  6]
[24  2 44 56  6]


In [142]:
# cann not be perform bcz differnt length
a = np.array([2,22,4,5,6])
b = np.array([24,2,44,56,6,4])
print(a)
print(b)

[ 2 22  4  5  6]
[24  2 44 56  6  4]


In [140]:
# add():
np.add(a,b)

array([26, 24, 48, 61, 12])

In [187]:
# subtract():
np.subtract(a,b)

array([ 1, 20,  1,  1,  1])

In [144]:
a = np.array([2,22,4,5,6])
b = np.array([24,2,44,56,6])
np.multiply(a,b)

array([ 48,  44, 176, 280,  36])

In [147]:
# divide() :- return quotient value
a = np.array([2,22,4,5,6])
b = np.array([24,2,44,56,6])
np.divide(a,b)

array([ 0.08333333, 11.        ,  0.09090909,  0.08928571,  1.        ])

In [148]:
# floor_divide() :- return int value
a = np.array([2,22,4,5,6])
b = np.array([24,2,44,56,6])
np.floor_divide(a,b)

array([ 0, 11,  0,  0,  1])

In [151]:
#mod()
np.mod(a,b)

array([2, 0, 4, 5, 0])

In [152]:
#divmod()
np.divmod(a,b)

(array([ 0, 11,  0,  0,  1]), array([2, 0, 4, 5, 0]))

In [154]:
#sqrt() 
np.sqrt(a)

array([1.41421356, 4.69041576, 2.        , 2.23606798, 2.44948974])

In [155]:
#power(array,exponent)
np.power(b,2)

array([ 576,    4, 1936, 3136,   36])

In [156]:
#log()
np.log(a)

array([0.69314718, 3.09104245, 1.38629436, 1.60943791, 1.79175947])

In [157]:
#sin()
np.sin(a)

array([ 0.90929743, -0.00885131, -0.7568025 , -0.95892427, -0.2794155 ])

In [158]:
#cos()
np.cos(a)

array([-0.41614684, -0.99996083, -0.65364362,  0.28366219,  0.96017029])

In [159]:
#tan()
np.tan(a)

array([-2.18503986,  0.00885166,  1.15782128, -3.38051501, -0.29100619])

In [160]:
# exp():
np.exp(a)

array([7.38905610e+00, 3.58491285e+09, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02])

In [162]:
# Statistical Operation on array.
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [164]:
# max()
np.max(b)

np.int64(5)

In [165]:
#min()
np.min(b)

np.int64(1)

In [166]:
# mean(): avg
np.mean(b)

np.float64(3.0)

In [167]:
# median():
np.median(b)

np.float64(3.0)

In [168]:
# argmax(): return the index of maximum value
np.argmax(b)

np.int64(4)

In [169]:
# argmin(): return the index of minmum value in your array
np.argmin(b)

np.int64(0)

In [170]:
# std(): standard deviation 
np.std(b)

np.float64(1.4142135623730951)

In [173]:
#cumsum: cummulative summation
b = np.array([1,2,3,4,5])
np.cumsum(b)

array([ 1,  3,  6, 10, 15])

In [175]:
#cumprod: cummulative product
b = np.array([1,2,3,4,5])
np.cumprod(b)

array([  1,   2,   6,  24, 120])

In [176]:
#cumproduct: cummulative product
b = np.array([1,2,3,4,5])
np.cumproduct(b)

AttributeError: module 'numpy' has no attribute 'cumproduct'

In [178]:
# repeat():- repeats each element for the given array
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [179]:
# repeat()
np.repeat(b,2)

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [182]:
# tile() :- repeats the whole sequence for given array
np.tile(b,3)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [185]:
# where():returns the index of specific elements .
x = np.array([1,2,3,3,6,2,7,3,8,7,9,5,5,3,5])
np.where(x==3)  #print index position

(array([ 2,  3,  7, 13]),)